### ISSUE TITLE
[SUGGESTION] and [BUG]

### ISSUE THREAD

**Issue by Teddyymc** [WurstPlus/wurst-plus-three#220]
-holefill doesn't disable when there is an entity in the hole. Quite annoying cuz it'll fill your own hole when you get out.
-Nametags durability cause "opengl error : 1283 (stack overflow)" and make big render issues on servers like 9b
-Everything realated to popcounter (on nametags, on logoutspot and in chat) doesnt work in the last build
-Add non-compact popcounter for different ppl like phobos
-More settings for offhand maybe add switch key for gapps etc and holehp doesn't work

**Comment by amongusenjoyer69** [comment]
-logoutspots could be compatibility issue
-a ca antistuck was made by wallhacks but it was shit so it was removed, explain what an antistuck should do

**Comment by Teddyymc** [comment]
Yeah I feel that the anti stuck that wallhack made resolved most of my issues. Sometimes my ca just stop or try to place a crystal right next to an other one making it stop for a few sec. ( not an range issue or a break/place delay issue) And for logoutspot I'll try to see which other client may cause that issue

**Comment by amongusenjoyer69** [comment]
no, antistuck did not work at all https://streamable.com/ew62dz

an outraged travis gladly removed it

**Comment by amongusenjoyer69** [comment]
> Yeah I feel that the anti stuck that wallhack made resolved most of my issues. Sometimes my ca just stop or try to place a crystal right next to an other one making it stop for a few sec. ( not an range issue or a break/place delay issue) And for logoutspot I'll try to see which other client may cause that issue

I asked for a max self break dmg but apparently that didn’t work as I expected to, so I guess you just have to rely on your skill and a good dmg config to avoid stuff like that happening.

**Comment by Teddyymc** [comment]
I don't think it's a skill issue cuz it happens a lot when my opponent is in a hole and his health drop below my tabbot settings or armor fuckur is enabled so the ca start to face place then randomly stop. Like it try to place + there is the block highlight but it just pause. 
Can anti stuck is the least important thing in my opinion.
Hole fill is particularly annoying and nametags durability too

**Comment by amongusenjoyer69** [comment]
I see what you mean, this is a desync that is caused by (I assume) fast mode ghost. Set it to sound.

**Comment by amongusenjoyer69** [comment]
If that’s not a case, then it’s concerning. Hopefully it is fixed.

**Comment by Teddyymc** [comment]
I already have it on sound but ca antistuck isn't a big deal for me 
But the others are :)

**Comment by wallhacks0** [comment]
The anti stuck did nothing it all cus I did oopsie in code and when i got it working ca became china

**Comment by wallhacks0** [comment]
offhand recently got improved already
logoutspot works for me could you make a video or something to show whats happening with it?
speedmine seems to still work for me maybe thats a config issue

**Comment by Teddyymc** [comment]
Sure I'll send a video about speed mine and logoutspot when I'm home

**Comment by amongusenjoyer69** [comment]
> offhand recently got improved already
> logoutspot works for me could you make a video or something to show whats happening with it?
> speedmine seems to still work for me maybe thats a config issue

you still wanna add options to offhand though like teddy said, a key gap is a good idea, maybe totem on ely and a fall check

**Comment by wallhacks0** [comment]
explain what keygap would do and il think about it, Il do the fall check rn and the fall check will make elytra also only have totem

**Comment by amongusenjoyer69** [comment]
> explain what keygap would do and il think about it, Il do the fall check rn and the fall check will make elytra also only have totem

Key gap is supposed to bind offhand gap to a key, this is useful for servers like oldfag where you need an offhand gap most of the time. I would also like to point out that hole hp is so fucked, if you have it lower than your normal hp it will crash your game when you are in a hole.

**Comment by wallhacks0** [comment]
thanks for pointing that out

**Comment by wallhacks0** [comment]
could you send a crashlog i have never had this problem myself

**Comment by wallhacks0** [comment]
and keygap is not needed you can have mode to totem and have gapswap on always

**Comment by amongusenjoyer69** [comment]
yeah okay my bad it seems like it doesn’t crash anymore, but it doesn’t work. I assume hole hp changes the totem swap hp when you’re in a hole. Despite having my hole hp on 2 it is still swapping to a totem at 15 hp

**Comment by wallhacks0** [comment]
that sounds like impossible

**Comment by amongusenjoyer69** [comment]
okay this is very hard to explain let me just send you a video

**Comment by wallhacks0** [comment]
if ((hp > TotemHp.getValue() || (EntityUtil.isInHole(mc.player) && hp > HoleHP.getValue())) && lethalToLocalCheck() && Check32K()) {

**Comment by amongusenjoyer69** [comment]
https://streamable.com/x0pvfs

**Comment by amongusenjoyer69** [comment]
i can assure you i have no other offhand on at the same time

**Comment by amongusenjoyer69** [comment]
the first time i tested it, it simply didn't work, it just desynced me and turned all my crystals into totems

after that it didn't desync me but instead kicked me from the server (as you can see in the video above)

**Comment by Teddyymc** [comment]
Yeah hole HP doesn't work for me neither and gapswap always isn't the same thing than with a key. For instance when you try to place a crystal with a pick in your main hand it will not work because your offhand will switch from a crystal to a gap. Maybe you can look at autototem and offhand in salhack

**Comment by wallhacks0** [comment]
so explain exactly what you want gapswap key to do. switch between crystal and gap mode??

**Comment by Teddyymc** [comment]
Put a gap in your offhand when enabled and put back the offhand item when disabled

**Comment by wallhacks0** [comment]
so should it be a hold or a toggle bind

**Comment by Teddyymc** [comment]
Toggle but maybe make both like in other wp3 modules

**Comment by Teddyymc** [comment]
pleezzz fix this <3

**Comment by Madmegsox1** [comment]
Bugs have been fixed, name tags may be rewritten if I have time

**Comment by Teddyymc** [comment]
Holefill is still an issue even on 0.7.0.
And the popcounter issue is only when I use the latest 0.7.0 version. It appeared sins popchams.
And the other things are only enhancement

**Comment by Teddyymc** [comment]
OK nvm I saw why popcounter doesn't  work in #264
